version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf:/etc/nginx/conf.d
    ports:
      - 6566:6566
    command: "nginx -c /etc/nginx/conf.d/nginx.conf"
