version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    ports:
      - 8081:8081
    restart: always

#version: "3.7"
#
#services:
#  db:
#    container_name: mongoDb
#    image: mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_DATABASE=auth
#      - MONGO_INITDB_ROOT_PASSWORD=pass
#    networks:
#      - mongodb-network
#    ports:
#      - '27017:27017'
#    restart: always
#    volumes:
#      - ./data:/data/db
#
#  mongo-express:
#    container_name: mongo-express
#    image: mongo-express:0.54
#    depends_on:
#      - db
#    networks:
#      - mongodb-network
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=mongoDb
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
#      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#      - ME_CONFIG_BASICAUTH_USERNAME=admin
#      - ME_CONFIG_BASICAUTH_PASSWORD=pass
#    ports:
#      - '8081:8081'
#    restart: always
#    volumes:
#      - ./data:/data/db
#
#networks:
#  mongodb-network:
#    driver: bridge
