version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      - MONGO_INITDB_DATABASE=rsocket
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_DATABASE=rsocket
    volumes:
      - ./data/dbstore/mongodb/:/data/db/
      - ./setup/mongodb/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    networks:
      - mongo-network
    ports:
      - 27017:27017
    expose:
      - '27017'
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    volumes:
      - ./data/dbstore/mongodb/:/data/db/
    #    links:
    #      - mongodb
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - mongo-network

networks:
  postgres-network:
  mongo-network:


volumes:
  databases: